window.SETTLEMENT_DATA = {
  "version": "2026-08-07-v5-public-1",
  "generatedAt": "2026-08-07T13:44:01.326Z",
  "categories": [
    "항공",
    "숙박",
    "렌터카",
    "콜밴",
    "외식·카페",
    "관광·입장",
    "식료품",
    "주차",
    "쇼핑·기념품",
    "의약·편의",
    "확인필요",
    "비여행"
  ],
  "items": [
    {
      "id": "item-072",
      "date": "2025-08-09",
      "merchant": "대한항공",
      "description": "왕복 항공권 4명",
      "category": "항공",
      "billingPeriod": "사전결제 완료",
      "included": true,
      "usd": 6362.150296381571,
      "krw": 9398600
    },
    {
      "id": "item-073",
      "date": "2025-08-09",
      "merchant": "대한항공",
      "description": "유료 좌석 4명분",
      "category": "항공",
      "billingPeriod": "사전결제 완료",
      "included": true,
      "usd": 406.1551909676912,
      "krw": 600000
    },
    {
      "id": "item-074",
      "date": "2026-04-14",
      "merchant": "LAFC",
      "description": "경기 티켓 4매",
      "category": "관광·입장",
      "billingPeriod": "사전결제 완료",
      "included": true,
      "usd": 837.72,
      "krw": 1237537
    },
    {
      "id": "item-076",
      "date": "2026-06-07",
      "merchant": "Disney California Adventure",
      "description": "1일 티켓 4매",
      "category": "관광·입장",
      "billingPeriod": "사전결제 완료",
      "included": true,
      "usd": 733.5839674194783,
      "krw": 1083700
    },
    {
      "id": "item-075",
      "date": "2026-06-07",
      "merchant": "Universal Studios Hollywood",
      "description": "테마파크 티켓 4매",
      "category": "관광·입장",
      "billingPeriod": "사전결제 완료",
      "included": true,
      "usd": 530.4386794038047,
      "krw": 783600
    },
    {
      "id": "item-078",
      "date": "2026-07-19",
      "merchant": "인천공항 왕복 콜밴",
      "description": "동탄-인천공항 왕복",
      "category": "콜밴",
      "billingPeriod": "사전결제 완료",
      "included": true,
      "usd": 148.92357002148677,
      "krw": 220000
    },
    {
      "id": "item-002",
      "date": "2026-07-20",
      "merchant": "Knott's Berry Farm",
      "description": "PAYPAL *KNOTTSBERRY",
      "category": "관광·입장",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 276,
      "krw": 418337
    },
    {
      "id": "item-003",
      "date": "2026-07-24",
      "merchant": "In-N-Out",
      "description": "IN-N-OUT STUDIO CITY",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 48.4,
      "krw": 72318
    },
    {
      "id": "item-004",
      "date": "2026-07-25",
      "merchant": "Blue Bottle Coffee",
      "description": "SQ *BLUE BOTTLE COFF",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 14.75,
      "krw": 22036
    },
    {
      "id": "item-009",
      "date": "2026-07-25",
      "merchant": "BMO Stadium",
      "description": "BMO*6zuwihxjt",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 25.77,
      "krw": 38700
    },
    {
      "id": "item-010",
      "date": "2026-07-25",
      "merchant": "BMO Stadium",
      "description": "BMO*cpv11yte3",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 104.74,
      "krw": 157313
    },
    {
      "id": "item-011",
      "date": "2026-07-25",
      "merchant": "Fanatics / LAFC",
      "description": "FANATICS - LAFC HQ",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 729.71,
      "krw": 1095995
    },
    {
      "id": "item-006",
      "date": "2026-07-25",
      "merchant": "LAFC Parking",
      "description": "LAFC STADIUMCO LLC",
      "category": "주차",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 65,
      "krw": 97620
    },
    {
      "id": "item-007",
      "date": "2026-07-25",
      "merchant": "Natural History Museum LA",
      "description": "AT *NATHISTMUSEUMLAC",
      "category": "관광·입장",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 50,
      "krw": 75098
    },
    {
      "id": "item-008",
      "date": "2026-07-25",
      "merchant": "New Hop Li",
      "description": "NEW HOP LI",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 112.5,
      "krw": 168960
    },
    {
      "id": "item-005",
      "date": "2026-07-25",
      "merchant": "Trader Joe's",
      "description": "TRADER JOE S #122",
      "category": "식료품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 89.18,
      "krw": 133944
    },
    {
      "id": "item-013",
      "date": "2026-07-26",
      "merchant": "Cheesecake Factory",
      "description": "CHEESECAKE BEVERLY H",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 74.34,
      "krw": 111644
    },
    {
      "id": "item-017",
      "date": "2026-07-26",
      "merchant": "Hollywood Bazaar",
      "description": "HOLLYWOOD BAZAAR",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 3.78,
      "krw": 5628
    },
    {
      "id": "item-018",
      "date": "2026-07-26",
      "merchant": "Kino Sushi & Ramen",
      "description": "KINO SUSHI & RAMEN",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 167.85,
      "krw": 250039
    },
    {
      "id": "item-016",
      "date": "2026-07-26",
      "merchant": "LADOT Parking",
      "description": "LADOT PARKING",
      "category": "주차",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 17.5,
      "krw": 26065
    },
    {
      "id": "item-014",
      "date": "2026-07-26",
      "merchant": "Stussy",
      "description": "SP STUSSY LOS ANGELE",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 296.34,
      "krw": 445080
    },
    {
      "id": "item-015",
      "date": "2026-07-26",
      "merchant": "Stussy",
      "description": "SP STUSSY LOS ANGELE",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 246.94,
      "krw": 370888
    },
    {
      "id": "item-012",
      "date": "2026-07-26",
      "merchant": "Target T2479",
      "description": "TARGET STORE T2479",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 94.16,
      "krw": 141417
    },
    {
      "id": "item-021",
      "date": "2026-07-27",
      "merchant": "Animation Studio Store",
      "description": "ANIMATION STUDIO STO",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 136.09,
      "krw": 202725
    },
    {
      "id": "item-019",
      "date": "2026-07-27",
      "merchant": "Jurassic Cove",
      "description": "JURASSIC COVE",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 115.19,
      "krw": 171589
    },
    {
      "id": "item-024",
      "date": "2026-07-27",
      "merchant": "Smarte Carte",
      "description": "Universal Studios 라커",
      "category": "관광·입장",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 5,
      "krw": 7379
    },
    {
      "id": "item-022",
      "date": "2026-07-27",
      "merchant": "Starbucks",
      "description": "STARBUCKS (UL)",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 11.96,
      "krw": 17814
    },
    {
      "id": "item-023",
      "date": "2026-07-27",
      "merchant": "The Beverly Garland",
      "description": "호텔 내 스토어 식료품",
      "category": "식료품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 13.78,
      "krw": 20356
    },
    {
      "id": "item-020",
      "date": "2026-07-27",
      "merchant": "Universal Studios Store",
      "description": "USH UNIVERSL STUDIO",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 65.8,
      "krw": 98017
    },
    {
      "id": "item-025",
      "date": "2026-07-28",
      "merchant": "CVS",
      "description": "CVS/PHARMACY #10225",
      "category": "식료품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 165.63,
      "krw": 244708
    },
    {
      "id": "item-027",
      "date": "2026-07-28",
      "merchant": "Garden Terrace",
      "description": "GARDEN TERRACE",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 23.93,
      "krw": 34908
    },
    {
      "id": "item-026",
      "date": "2026-07-28",
      "merchant": "Getty Museum Store",
      "description": "GETTY MUSEUM STORE",
      "category": "관광·입장",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 16.41,
      "krw": 24243
    },
    {
      "id": "item-029",
      "date": "2026-07-28",
      "merchant": "The Beverly Garland",
      "description": "미니바 식료품",
      "category": "식료품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 16,
      "krw": 23335
    },
    {
      "id": "item-050",
      "date": "2026-07-28",
      "merchant": "The Garland",
      "description": "객실요금",
      "category": "숙박",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 1366.4,
      "krw": 1993609
    },
    {
      "id": "item-051",
      "date": "2026-07-28",
      "merchant": "The Garland",
      "description": "객실 관련 세금·호텔부담금",
      "category": "숙박",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 377.84,
      "krw": 551277
    },
    {
      "id": "item-052",
      "date": "2026-07-28",
      "merchant": "The Garland",
      "description": "주차 및 주차세",
      "category": "주차",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 220,
      "krw": 320985
    },
    {
      "id": "item-053",
      "date": "2026-07-28",
      "merchant": "The Garland",
      "description": "호텔 조식",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 99.41,
      "krw": 145042
    },
    {
      "id": "item-028",
      "date": "2026-07-28",
      "merchant": "Trader Joe's",
      "description": "TRADER JOE S #267",
      "category": "식료품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 119.99,
      "krw": 175053
    },
    {
      "id": "item-031",
      "date": "2026-07-29",
      "merchant": "Knott's Berry Farm",
      "description": "KNOTT'S BERRY ADMISS",
      "category": "관광·입장",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 52.5,
      "krw": 77257
    },
    {
      "id": "item-032",
      "date": "2026-07-29",
      "merchant": "Knott's Berry Farm",
      "description": "KNOTT'S BERRY MERCHA",
      "category": "관광·입장",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 30,
      "krw": 44153
    },
    {
      "id": "item-033",
      "date": "2026-07-29",
      "merchant": "Knott's Berry Farm",
      "description": "KNOTT'S BERRY FARM F",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 86.26,
      "krw": 126942
    },
    {
      "id": "item-034",
      "date": "2026-07-29",
      "merchant": "Knott's Berry Farm",
      "description": "KNOTT'S BERRY PARKIN",
      "category": "주차",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 40,
      "krw": 58871
    },
    {
      "id": "item-030",
      "date": "2026-07-29",
      "merchant": "Paris Baguette",
      "description": "TST* PARIS BAGUETTE",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 22.03,
      "krw": 32138
    },
    {
      "id": "item-044",
      "date": "2026-07-30",
      "merchant": "CVS",
      "description": "CVS/PHARMACY #10225",
      "category": "식료품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 91.64,
      "krw": 134862
    },
    {
      "id": "item-037",
      "date": "2026-07-30",
      "merchant": "Disneyland Resort",
      "description": "DLR AWARD WIENERS",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 92.26,
      "krw": 135779
    },
    {
      "id": "item-038",
      "date": "2026-07-30",
      "merchant": "Disneyland Resort",
      "description": "DLR MORTIMER MARKET",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 16.99,
      "krw": 24995
    },
    {
      "id": "item-039",
      "date": "2026-07-30",
      "merchant": "Disneyland Resort",
      "description": "DLR ELIAS & CO",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 36.61,
      "krw": 53877
    },
    {
      "id": "item-040",
      "date": "2026-07-30",
      "merchant": "Disneyland Resort",
      "description": "DLR ELIAS & CO",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 26.93,
      "krw": 39625
    },
    {
      "id": "item-041",
      "date": "2026-07-30",
      "merchant": "Disneyland Resort",
      "description": "DLR OSWALD'S",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 39.86,
      "krw": 58652
    },
    {
      "id": "item-042",
      "date": "2026-07-30",
      "merchant": "Disneyland Resort",
      "description": "DLR CAPPUCCINO SF",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 35.5,
      "krw": 52247
    },
    {
      "id": "item-043",
      "date": "2026-07-30",
      "merchant": "Disneyland Resort",
      "description": "DLR LIGHTNING LANE",
      "category": "관광·입장",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 92,
      "krw": 135401
    },
    {
      "id": "item-036",
      "date": "2026-07-30",
      "merchant": "Nayax Vending",
      "description": "포켓몬 카드 벤딩 머신",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 24.97,
      "krw": 36743
    },
    {
      "id": "item-035",
      "date": "2026-07-30",
      "merchant": "Polo Factory Store",
      "description": "Polo Factory Store O",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 850,
      "krw": 1240169
    },
    {
      "id": "item-047",
      "date": "2026-07-31",
      "merchant": "Adidas Irvine",
      "description": "adidas 6530 Irvine",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 150.84,
      "krw": 221990
    },
    {
      "id": "item-046",
      "date": "2026-07-31",
      "merchant": "Chipotle",
      "description": "CHIPOTLE 1026",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 14.26,
      "krw": 20977
    },
    {
      "id": "item-048",
      "date": "2026-07-31",
      "merchant": "Crocs",
      "description": "Crocs Irvine CA",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 26.91,
      "krw": 39596
    },
    {
      "id": "item-045",
      "date": "2026-07-31",
      "merchant": "Macy's",
      "description": "MACYS  SOUTH COAST",
      "category": "쇼핑·기념품",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 543.6,
      "krw": 800049
    },
    {
      "id": "item-049",
      "date": "2026-07-31",
      "merchant": "Pho Saigon Pearl",
      "description": "PHO SAIGON PEARL",
      "category": "외식·카페",
      "billingPeriod": "8월 명세서 반영",
      "included": true,
      "usd": 108.08,
      "krw": 158334
    },
    {
      "id": "item-054",
      "date": "2026-08-01",
      "merchant": "JW Marriott Anaheim",
      "description": "객실요금",
      "category": "숙박",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 1855.88,
      "krw": 2741632
    },
    {
      "id": "item-055",
      "date": "2026-08-01",
      "merchant": "JW Marriott Anaheim",
      "description": "객실 관련 세금·부담금",
      "category": "숙박",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 318.93,
      "krw": 471145
    },
    {
      "id": "item-056",
      "date": "2026-08-01",
      "merchant": "JW Marriott Anaheim",
      "description": "Destination fee 및 세금",
      "category": "숙박",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 187.2,
      "krw": 276545
    },
    {
      "id": "item-057",
      "date": "2026-08-01",
      "merchant": "JW Marriott Anaheim",
      "description": "주차 및 주차세·부담금",
      "category": "주차",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 322.92,
      "krw": 477039
    },
    {
      "id": "item-058",
      "date": "2026-08-01",
      "merchant": "JW Marriott Anaheim",
      "description": "In-Room Dining",
      "category": "외식·카페",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 232.09,
      "krw": 342859
    },
    {
      "id": "item-059",
      "date": "2026-08-03",
      "merchant": "Terranea Resort",
      "description": "Expedia 숙박 패키지",
      "category": "숙박",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 943.2600000000002,
      "krw": 1393448
    },
    {
      "id": "item-060",
      "date": "2026-08-03",
      "merchant": "Terranea Resort",
      "description": "In-Room Dining",
      "category": "외식·카페",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 384.16,
      "krw": 567507
    },
    {
      "id": "item-061",
      "date": "2026-08-03",
      "merchant": "Terranea Resort",
      "description": "Cielo Point",
      "category": "외식·카페",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 22.76,
      "krw": 33623
    },
    {
      "id": "item-062",
      "date": "2026-08-03",
      "merchant": "Terranea Resort",
      "description": "주차",
      "category": "주차",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 150,
      "krw": 221590
    },
    {
      "id": "item-077",
      "date": "",
      "merchant": "미국 eSIM",
      "description": "무제한 eSIM 2개",
      "category": "관광·입장",
      "billingPeriod": "사전결제 완료",
      "included": true,
      "usd": 41.15705935139271,
      "krw": 60800
    },
    {
      "id": "item-071",
      "date": "",
      "merchant": "City of Santa Ana Parking",
      "description": "명세서 미반영",
      "category": "주차",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 2,
      "krw": 2954
    },
    {
      "id": "item-066",
      "date": "",
      "merchant": "Crocs",
      "description": "$141.40 승인 상태 확인",
      "category": "쇼핑·기념품",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 141.4,
      "krw": 208886
    },
    {
      "id": "item-063",
      "date": "",
      "merchant": "Hertz",
      "description": "부분취소 반영 후 순승인",
      "category": "렌터카",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 1547.76,
      "krw": 2286456
    },
    {
      "id": "item-068",
      "date": "",
      "merchant": "In-N-Out",
      "description": "LA Mirada 구매분 미반영",
      "category": "외식·카페",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 34.24,
      "krw": 50582
    },
    {
      "id": "item-067",
      "date": "",
      "merchant": "Ralphs",
      "description": "명세서 미반영",
      "category": "식료품",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 75.34,
      "krw": 111297
    },
    {
      "id": "item-070",
      "date": "",
      "merchant": "Starbucks",
      "description": "Store 06897 구매분 미반영",
      "category": "외식·카페",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 10.399999999999999,
      "krw": 15364
    },
    {
      "id": "item-064",
      "date": "",
      "merchant": "Stussy",
      "description": "Archive 구매분 미반영",
      "category": "쇼핑·기념품",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 442.49,
      "krw": 653676
    },
    {
      "id": "item-079",
      "date": "",
      "merchant": "Terranea Resort",
      "description": "숙박 선결제",
      "category": "숙박",
      "billingPeriod": "사전결제 완료",
      "included": true,
      "usd": 1152.37,
      "krw": 1702359
    },
    {
      "id": "item-065",
      "date": "",
      "merchant": "Trader Joe's",
      "description": "#233 구매분 미반영",
      "category": "식료품",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 164.7,
      "krw": 243306
    },
    {
      "id": "item-069",
      "date": "",
      "merchant": "Wetzel's Pretzels",
      "description": "명세서 미반영",
      "category": "외식·카페",
      "billingPeriod": "9월 명세서 예상",
      "included": true,
      "usd": 13.66,
      "krw": 20179
    }
  ]
};
